server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/webflux
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/webflux
    locations: classpath:db/migration
    user: postgres
    password: root
    baselineOnMigrate: true

jwt:
  password:
    encoder:
      secret: veryBigSecret_256
      iteration: 64
      keyLength: 256
  secret: 112365898774sed4556effgtg9855fggg4hhu4ui
  expiration: 3600
  issuer: proselyte
